_target_: vc_models.models.load_model
model:
  _target_: vc_models.models.diffusion_model.load_sd_model
  model_name: "runwayml/stable-diffusion-v1-5"
  unet_path: /path/to/stable_diffusion/unet_ema 
  noise_sampling: "per_image"
  representation_layer_name:
    - "down_1"
    - "down_2"
    - "down_3"
    - "mid"
  timestep:
    - 0
  tokenize_captions: True
  get_attention_maps: False
  get_word_level_heat_map: False
  use_cached_encoder_hidden_states: False
  encoder_hidden_states_path: "data/objects/sd_clip_embeddings.pickle"
  num_token_attn: 2
  input_image_size: 256
  flatten: True
  dtype: float16
transform:
  _target_: vc_models.transforms.diffusion_transforms
  resize_size: 256
metadata:
  algo: diffusion
  model: sd_15
  data: laion
