_target_: vc_models.models.load_model
model:
  _target_: vc_models.models.sd_vae.load_sd_vae_model
  model_name_or_path: "runwayml/stable-diffusion-v1-5"
  input_image_size: 256
  flatten: True
transform:
  _target_: vc_models.transforms.diffusion_transforms
  resize_size: 256
metadata:
  algo: vae
  model: sd_15
  data: laion
